#region Copyright & License

// Copyright © 2020 - 2022 Emmanuel Benitez
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#endregion

using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ValueGeneration;

namespace BigSolution.Persistence.ValueGenerators;

/// <summary>
/// Represents a value generator that produces the current UTC date and time as a <see cref="DateTimeOffset"/>.
/// </summary>
/// <remarks>
/// This generator is designed to provide non-temporary values, specifically the current UTC date and time, 
/// for use in scenarios such as auditing or timestamping.
/// </remarks>
public class NowDateTimeOffsetValueGenerator : ValueGenerator<DateTimeOffset>
{
    #region Base Class Member Overrides

    /// <summary>
    /// Generates the next value, which is the current UTC date and time as a <see cref="DateTimeOffset"/>.
    /// </summary>
    /// <param name="entry">The <see cref="EntityEntry"/> instance for which the value is being generated.</param>
    /// <returns>The current UTC date and time as a <see cref="DateTimeOffset"/>.</returns>
    /// <remarks>
    /// This method overrides the base implementation to provide a non-temporary value, specifically the current UTC date and time.
    /// </remarks>
    public override DateTimeOffset Next(EntityEntry entry)
    {
        return DateTimeOffset.UtcNow;
    }

    #endregion

    #region Base Class Member Overrides

    /// <summary>
    /// Gets a value indicating whether the values generated are temporary.
    /// </summary>
    /// <value>
    /// Always returns <c>false</c>, as this generator produces non-temporary values.
    /// </value>
    /// <remarks>
    /// This property indicates that the values generated by this generator are intended to be permanent and 
    /// should not be replaced by the database when the entity is saved.
    /// </remarks>
    public override bool GeneratesTemporaryValues => false;

    #endregion
}
